SET search_path = kyc;
-- Merge house_number into street in address table
UPDATE company
SET street =
        CASE
            WHEN street IS NULL AND house_number IS NULL THEN NULL
            WHEN street IS NULL THEN house_number
            WHEN house_number IS NULL OR house_number = '' THEN street
            ELSE street || ' ' || house_number
            END;

ALTER TABLE company DROP COLUMN house_number;

-- Director: add registered and hasKboAddress
ALTER TABLE director ADD registered boolean NOT NULL DEFAULT FALSE;
ALTER TABLE company ADD suspended boolean NOT NULL DEFAULT FALSE;
ALTER TABLE company ADD has_kbo_address boolean NOT NULL DEFAULT TRUE;
UPDATE director SET registered = true WHERE 1=1;

-- KBO processed zip files
CREATE TABLE IF NOT EXISTS kbo_processed_zip (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename     varchar(255) NOT NULL UNIQUE,
    processed_at timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_kbo_processed_zip_filename ON kbo_processed_zip(filename);
