SET search_path = kyc;

CREATE TYPE ownership_status AS ENUM ('ACTIVE', 'INVITED', 'SUSPENDED');

ALTER TABLE ownership
    ADD COLUMN status          ownership_status NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN permission_mask integer          NOT NULL DEFAULT 0;

UPDATE ownership SET permission_mask = 255 WHERE type = 'USER';

CREATE TABLE ownership_invitation (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ownership_id          bigint NOT NULL UNIQUE,
    invited_by_account_id bigint,
    invited_name          varchar(255) NOT NULL,
    token                 varchar(64) NOT NULL UNIQUE,
    expires_on            timestamp with time zone NOT NULL,
    created_on            timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT fk_ownership_invitation_ownership
        FOREIGN KEY (ownership_id) REFERENCES ownership(id) ON DELETE CASCADE,
    CONSTRAINT fk_ownership_invitation_invited_by
        FOREIGN KEY (invited_by_account_id) REFERENCES account(id) ON DELETE SET NULL
);

CREATE INDEX idx_ownership_company_status ON ownership(company_id, status);
CREATE UNIQUE INDEX uq_ownership_user_per_company ON ownership(account_id, company_id) WHERE type = 'USER';
