-- Ownership (FK -> account, company)
CREATE TABLE IF NOT EXISTS ownership (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL,
  company_id bigint NOT NULL,
  type       account_type NOT NULL,
  created_on timestamp with time zone NOT NULL,
  last_used  timestamp with time zone NOT NULL,

  CONSTRAINT fk_ownership_account
    FOREIGN KEY (account_id) REFERENCES account(id) ON DELETE CASCADE,
  CONSTRAINT fk_ownership_company
    FOREIGN KEY (company_id) REFERENCES company(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ownership_account_id         ON ownership(account_id);
CREATE INDEX IF NOT EXISTS idx_ownership_company_id         ON ownership(company_id);
CREATE INDEX IF NOT EXISTS idx_ownership_company_type       ON ownership(company_id, type);
CREATE INDEX IF NOT EXISTS idx_ownership_account_type       ON ownership(account_id, type);
CREATE INDEX IF NOT EXISTS idx_ownership_account_last_used  ON ownership(account_id, last_used DESC);

ALTER TABLE email_verification
  ADD COLUMN requester_ownership_id bigint,
  ADD COLUMN type account_type NOT NULL DEFAULT 'ADMIN',
  ADD CONSTRAINT fk_email_verification_ownership
      FOREIGN KEY (requester_ownership_id) REFERENCES ownership(id) ON DELETE CASCADE;

-- Backfill from account -> ownership
INSERT INTO ownership (account_id, company_id, type, created_on, last_used)
SELECT account.id, account.company_id, account.type, COALESCE(account.created_on, now()), COALESCE(account.created_on, now())
FROM account
WHERE account.company_id IS NOT NULL
  AND account.type IS NOT NULL;

-- Backfill from account_link -> ownership
INSERT INTO ownership (account_id, company_id, type, created_on, last_used)
SELECT account_link.linked_account_id, account.company_id, account.type, COALESCE(account_link.created_on, now()), COALESCE(account_link.created_on, now())
FROM account_link JOIN account ON account_link.account_id = account.id;

-- Drop old indexes
DROP INDEX IF EXISTS idx_company_peppol_id;
DROP INDEX IF EXISTS idx_account_company_id;
DROP INDEX IF EXISTS idx_account_company_email;
DROP INDEX IF EXISTS idx_account_link_account_id;
DROP INDEX IF EXISTS idx_account_link_linked_account_id;

-- Drop old columns
ALTER TABLE account
  DROP COLUMN IF EXISTS company_id,
  DROP COLUMN IF EXISTS type;

-- Drop old table
DROP TABLE account_link;

-- Rename AccountIdentityVerification to DirectorIdentityVerification
ALTER TABLE account_identity_verification
  RENAME TO director_identity_verification;

ALTER TABLE director_identity_verification
  RENAME CONSTRAINT fk_account_identity_verification_account
  TO fk_director_identity_verification_account;

ALTER TABLE director_identity_verification
  RENAME CONSTRAINT fk_account_identity_verification_director
  TO fk_director_identity_verification_director;

ALTER INDEX IF EXISTS idx_account_identity_verification_account_id
  RENAME TO idx_director_identity_verification_account_id;

ALTER INDEX IF EXISTS idx_account_identity_verification_director_id
  RENAME TO idx_director_identity_verification_director_id;
