CREATE TYPE account_type AS ENUM ('ADMIN', 'USER', 'USER_DRAFT', 'USER_READ', 'APP', 'APP_USER', 'ACCOUNTANT');

ALTER TABLE account ADD COLUMN type account_type NOT NULL DEFAULT 'ADMIN';
ALTER TABLE company ALTER COLUMN peppol_id varchar(255) UNIQUE DEFAULT NULL;
