SET search_path = kyc;

CREATE TABLE passkey_credential (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id          bigint NOT NULL,
    credential_id       bytea NOT NULL,
    public_key_cose     bytea NOT NULL,
    sign_count          bigint NOT NULL DEFAULT 0,
    transports          varchar(255),
    display_name        varchar(255) NOT NULL,
    aaguid              uuid,
    discoverable        boolean NOT NULL DEFAULT TRUE,
    created_on          timestamp with time zone NOT NULL DEFAULT now(),
    last_used_on        timestamp with time zone,
    CONSTRAINT fk_passkey_credential_account
        FOREIGN KEY (account_id) REFERENCES account(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX idx_passkey_credential_credential_id ON passkey_credential(credential_id);
CREATE INDEX idx_passkey_credential_account_id ON passkey_credential(account_id);
