CREATE SCHEMA IF NOT EXISTS kyc;
SET search_path = kyc;

-- Company
CREATE TABLE company (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    peppol_id               varchar(255) UNIQUE NOT NULL,
    vat_number              varchar(255),
    name                    varchar(255) NOT NULL,
    city                    varchar(255),
    house_number            varchar(255),
    postal_code             varchar(255),
    registered_on_peppol    boolean NOT NULL,
    street                  varchar(255)
);

-- Director (FK -> company)
CREATE TABLE director (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255) NOT NULL,
    company_id  bigint NOT NULL,
    CONSTRAINT fk_director_company
        FOREIGN KEY (company_id) REFERENCES company(id)
);

-- Account (FK -> company)
CREATE TABLE account (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id              bigint NOT NULL,
    name                    varchar(255) NOT NULL,
    email                   varchar(255) NOT NULL,
    password_hash           varchar(255) NOT NULL,
    created_on              timestamp with time zone NOT NULL,
    identity_verified       boolean NOT NULL,
    identity_verified_on    timestamp with time zone,
    external_id             uuid NOT NULL,
    CONSTRAINT fk_account_company
        FOREIGN KEY (company_id) REFERENCES company(id)
);

-- AccountIdentityVerification (FK -> account)
CREATE TABLE account_identity_verification (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id              bigint NOT NULL,
    director_id             bigint NOT NULL,
    director_name_snapshot  varchar(255) NOT NULL,
    certificate_subject     varchar(255) NOT NULL,
    certificate_serial      varchar(255) NOT NULL,
    signature_algorithm     varchar(255) NOT NULL,
    data_hash               varchar(255) NOT NULL,
    certificate             text NOT NULL,
    signature               text NOT NULL,
    created_on              timestamp with time zone NOT NULL,
    CONSTRAINT fk_account_identity_verification_account
        FOREIGN KEY (account_id) REFERENCES account(id),
    CONSTRAINT fk_account_identity_verification_director
        FOREIGN KEY (director_id) REFERENCES director(id)
);

-- EmailVerification
CREATE TABLE email_verification (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           varchar(255) NOT NULL,
    peppol_id       varchar(255) NOT NULL,
    token           varchar(255) UNIQUE NOT NULL,
    verified        boolean NOT NULL,
    expires_on      timestamp with time zone NOT NULL,
    created_on      timestamp with time zone NOT NULL
);

-- PasswordResetToken (FK -> account)
CREATE TABLE password_reset_token (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  bigint NOT NULL,
    token       varchar(255) UNIQUE NOT NULL,
    expires_on  timestamp with time zone NOT NULL,
    created_on  timestamp with time zone NOT NULL,
    used_on     timestamp with time zone,
    CONSTRAINT fk_password_reset_token_account
        FOREIGN KEY (account_id) REFERENCES account(id)
);

-- Helpful indexes (Postgres does NOT auto-index FKs)
CREATE INDEX idx_director_company_id                        ON director(company_id);
CREATE INDEX idx_account_company_id                         ON account(company_id);
CREATE INDEX idx_account_identity_verification_account_id   ON account_identity_verification(account_id);
CREATE INDEX idx_account_identity_verification_director_id  ON account_identity_verification(director_id);
CREATE INDEX idx_password_reset_token_account_id            ON password_reset_token(account_id);
-- Helpful indexes
CREATE INDEX idx_company_peppol_id                          ON company(peppol_id);
CREATE INDEX idx_email_verification_peppol_id               ON email_verification(peppol_id);
CREATE INDEX idx_account_company_email                      ON account(company_id,email);
CREATE INDEX idx_account_external_id                        ON account(external_id);
CREATE INDEX idx_password_reset_token_token                 ON password_reset_token(token);
