CREATE TYPE vat_ruleset AS ENUM (
    'VAT_REGISTERED',
    'VAT_EXEMPT_ART_56BIS',
    'VAT_EXEMPT_ART_44'
);

ALTER TABLE company
    ADD COLUMN vat_ruleset vat_ruleset NOT NULL DEFAULT 'VAT_REGISTERED';

CREATE TABLE invoice_vat_reason_usage (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active                    boolean DEFAULT true NOT NULL,
    created_on                timestamp with time zone,
    last_updated_on           timestamp with time zone,
    invoice_uid               uuid NOT NULL,
    selected_tax_category_id  varchar(16),
    written_reason            text,
    CONSTRAINT fk_invoice_vat_reason_usage_document
        FOREIGN KEY (invoice_uid) REFERENCES document(id) ON DELETE CASCADE
);

CREATE INDEX idx_invoice_vat_reason_usage_invoice_uid ON invoice_vat_reason_usage(invoice_uid);
CREATE INDEX idx_invoice_vat_reason_usage_created_on ON invoice_vat_reason_usage(created_on);
