CREATE TABLE sponsor_invoice (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active            boolean DEFAULT true NOT NULL,
    created_on        timestamp with time zone,
    last_updated_on   timestamp with time zone,
    company_id        bigint NOT NULL,
    sponsored_on      timestamp with time zone NOT NULL,
    amount            numeric(38,2) NOT NULL,
    currency          varchar(3) NOT NULL,
    name              varchar(255) NOT NULL,
    message           text,
    invoice_id        varchar(255) UNIQUE NOT NULL,
    CONSTRAINT fk_sponsor_invoice_company
        FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE INDEX idx_sponsor_invoice_company_id ON sponsor_invoice(company_id);
CREATE INDEX idx_sponsor_invoice_sponsored_on ON sponsor_invoice(sponsored_on);
