CREATE TABLE accountant_customer (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accountant_external_id      uuid NOT NULL,
    customer_peppol_id          varchar(255) DEFAULT NULL,
    customer_email              varchar(255) DEFAULT NULL,
    customer_name               varchar(255) DEFAULT NULL,
    token                       varchar(255) DEFAULT NULL,
    invited_on                  timestamp with time zone,
    verified_on                 timestamp with time zone,
    last_download_created_on    timestamp with time zone,
    last_download_issued_on     timestamp with time zone
);
