CREATE TYPE notification_group AS ENUM ('USER', 'SPECIAL', 'SPONSOR', 'EDITOR', 'ONCE');

ALTER TABLE company
    ADD COLUMN notification_group notification_group DEFAULT 'USER' NOT NULL;

CREATE TABLE welcome_notification (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active            boolean DEFAULT true NOT NULL,
    created_on        timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_on   timestamp with time zone,
    html_code_en      text NOT NULL,
    html_code_nl      text NOT NULL,
    html_code_fr      text NOT NULL,
    html_code_de      text NOT NULL,
    notification_group notification_group DEFAULT 'USER' NOT NULL
);

CREATE INDEX idx_welcome_notification_group_active_created_on
    ON welcome_notification(notification_group, active, created_on);

UPDATE company
SET notification_group = 'SPONSOR'
WHERE id IN (
    SELECT DISTINCT company_id
    FROM sponsor_invoice
    WHERE active = true
);
