CREATE TYPE vat_ruleset AS ENUM (
    'VAT_REGISTERED',
    'VAT_EXEMPT_ART_56BIS',
    'VAT_EXEMPT_ART_44'
);

ALTER TABLE company
    ADD COLUMN vat_ruleset vat_ruleset NOT NULL DEFAULT 'VAT_REGISTERED';

CREATE TABLE invoice_vat_reason_selection (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active                    boolean DEFAULT true NOT NULL,
    created_on                timestamp with time zone,
    last_updated_on           timestamp with time zone,
    invoice_uid               uuid,
    selected_tax_category_id  varchar(16),
    written_reason            text,
    during_draft              boolean DEFAULT false NOT NULL,
    CONSTRAINT fk_invoice_vat_reason_selection_document
        FOREIGN KEY (invoice_uid) REFERENCES document(id) ON DELETE CASCADE
);

CREATE INDEX idx_invoice_vat_reason_selection_invoice_uid ON invoice_vat_reason_selection(invoice_uid);
CREATE INDEX idx_invoice_vat_reason_selection_created_on ON invoice_vat_reason_selection(created_on);
CREATE INDEX idx_invoice_vat_reason_selection_during_draft ON invoice_vat_reason_selection(during_draft);
