CREATE TABLE download_job (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active                boolean DEFAULT true NOT NULL,
    created_on            timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_on       timestamp with time zone,
    company_id            bigint NOT NULL,
    from_date             date NOT NULL,
    to_date               date NOT NULL,
    status                varchar(32) NOT NULL,
    archive_filename      varchar(255),
    archive_path          varchar(1024),
    completed_on          timestamp with time zone,
    expires_on            timestamp with time zone,
    processing_started_on timestamp with time zone,
    download_count        integer NOT NULL DEFAULT 0,
    failure_message       text,
    CONSTRAINT fk_download_job_company
        FOREIGN KEY (company_id) REFERENCES company(id) ON DELETE CASCADE,
    CONSTRAINT ck_download_job_date_order CHECK (from_date <= to_date),
    CONSTRAINT ck_download_job_download_count CHECK (download_count >= 0 AND download_count <= 3)
);

CREATE INDEX idx_download_job_company_created
    ON download_job(company_id, created_on DESC);
CREATE INDEX idx_download_job_expiry
    ON download_job(expires_on)
    WHERE status = 'READY';
CREATE INDEX idx_download_job_pending
    ON download_job(status, processing_started_on)
    WHERE status IN ('PENDING', 'PROCESSING');
