ALTER TABLE company
    ADD COLUMN enable_email_notification boolean DEFAULT false NOT NULL,
    ADD COLUMN add_attachment_to_notification boolean DEFAULT false NOT NULL,
    ADD COLUMN email_notification_cc_list varchar(255);

CREATE TABLE email_job (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active          boolean DEFAULT true NOT NULL,
    created_on      timestamp with time zone,
    last_updated_on timestamp with time zone,
    status          varchar(15),
    template        varchar(31),
    to_address      varchar(255),
    sent_at         timestamp with time zone,
    payload         jsonb
);
