CREATE SCHEMA IF NOT EXISTS app;
SET search_path = app;

-- Enums
CREATE TYPE document_direction AS ENUM ('INCOMING', 'OUTGOING');
CREATE TYPE document_type AS ENUM ('INVOICE', 'CREDIT_NOTE');

-- Address
CREATE TABLE address (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active            boolean DEFAULT true NOT NULL,
    created_on        timestamp with time zone,
    last_updated_on   timestamp with time zone,
    city              varchar(255),
    country_code      varchar(255),
    house_number      varchar(255),
    postal_code       varchar(255),
    street            varchar(255)
);

-- Company (FK -> address)
CREATE TABLE company (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active                  boolean DEFAULT true NOT NULL,
    created_on              timestamp with time zone,
    last_updated_on         timestamp with time zone,
    company_number          varchar(255) UNIQUE NOT NULL,
    iban                    varchar(255),
    name                    varchar(255) NOT NULL,
    payment_account_name    varchar(255),
    payment_terms           varchar(255),
    registered_on_peppol    boolean NOT NULL,
    subscriber              varchar(255),
    subscriber_email        varchar(255),
    registered_office_id    bigint UNIQUE NOT NULL,
    CONSTRAINT fk_company_registered_office
        FOREIGN KEY (registered_office_id) REFERENCES address(id)
);

-- Document (FK -> company)
CREATE TABLE document (
    id                  uuid PRIMARY KEY,
    direction           document_direction NOT NULL,
    owner_peppol_id     varchar(255) NOT NULL,
    partner_peppol_id   varchar(255) NOT NULL,
    proxy_on            timestamp with time zone,
    scheduled_on        timestamp with time zone,
    processed_on        timestamp with time zone,
    processed_status    varchar(255),
    ubl                 text,
    company_id          bigint NOT NULL,
    created_on          timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    drafted_on          timestamp with time zone,
    read_on             timestamp with time zone,
    paid_on             timestamp with time zone,
    partner_name        varchar(255) NOT NULL,
    invoice_reference   varchar(255) NOT NULL,
    buyer_reference     varchar(255),
    order_reference     varchar(255),
    type                document_type,
    currency            varchar(3) NOT NULL,
    amount              numeric,
    issue_date          timestamp with time zone,
    due_date            timestamp with time zone,
    payment_terms       varchar(255),
    CONSTRAINT fk_document_company
        FOREIGN KEY (company_id) REFERENCES company(id)
);

-- Partners (FK -> company, address)
CREATE TABLE partner (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active                  boolean DEFAULT true NOT NULL,
    created_on              timestamp with time zone,
    last_updated_on         timestamp with time zone,
    customer                boolean,
    email                   varchar(255),
    iban                    varchar(255),
    name                    varchar(255),
    payment_account_name    varchar(255),
    payment_terms           varchar(255),
    peppol_id               varchar(255),
    supplier                boolean,
    vat_number              varchar(255),
    company_id              bigint NOT NULL,
    registered_office_id    bigint UNIQUE NOT NULL,
    CONSTRAINT fk_partner_company
        FOREIGN KEY (company_id) REFERENCES company(id),
    CONSTRAINT fk_partner_registered_office
        FOREIGN KEY (registered_office_id) REFERENCES address(id)
);

-- Product_category (FK -> company, self FK -> product_category)
CREATE TABLE product_category (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active            boolean DEFAULT true NOT NULL,
    created_on        timestamp with time zone,
    last_updated_on   timestamp with time zone,
    color             varchar(255),
    name              varchar(255),
    company_id        bigint NOT NULL,
    parent_id         bigint,
    CONSTRAINT fk_category_company
        FOREIGN KEY (company_id) REFERENCES company(id),
    CONSTRAINT fk_category_parent
        FOREIGN KEY (parent_id) REFERENCES product_category(id)
);

-- Products (FK -> product_category, company)
CREATE TABLE product (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active            boolean DEFAULT true NOT NULL,
    created_on        timestamp with time zone,
    last_updated_on   timestamp with time zone,
    barcode           varchar(255),
    cost_price        numeric(38,2),
    description       varchar(255),
    name              varchar(255),
    reference         varchar(255),
    sale_price        numeric(38,2),
    stock_quantity    numeric(38,2),
    tax_percentage    numeric(38,2),
    category_id       bigint NOT NULL,
    company_id        bigint NOT NULL,
    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id) REFERENCES product_category(id),
    CONSTRAINT fk_product_company
        FOREIGN KEY (company_id) REFERENCES company(id)
);

-- Helpful indexes (Postgres does NOT auto-index FKs)
CREATE INDEX idx_document_company_id            ON document(company_id);
CREATE INDEX idx_category_company_id            ON product_category(company_id);
CREATE INDEX idx_category_parent_id             ON product_category(parent_id);
CREATE INDEX idx_partner_company_id             ON partner(company_id);
CREATE INDEX idx_partner_registered_office_id   ON partner(registered_office_id);
CREATE INDEX idx_company_registered_office_id   ON company(registered_office_id);
CREATE INDEX idx_product_company_id             ON product(company_id);
CREATE INDEX idx_product_category_id            ON product(category_id);
