openapi: 3.0.0
info:
  description: Add syncables to the Scrada Peppol API.
actions:
- target: $
  update:
    syncables:
      sendTransactions:
        description: |-
          Invoice and Credit Note Documents received by the authenticated user.
        type: collection
        get:
          path: /v1/company/{companyID}/peppol/inbound/document/unconfirmed
          field: results
          paging:
            countResponse: __count # total count. you can only retriev the first page. Use confirm to go to next page.
        confirm:
          path: /v1/company/{companyID}/peppol/inbound/document/{documentID}/confirm
          method: PUT